# Mise Command Runner to Run Examples
# Project dependencies: uv

[env]
VENV = ".venv"
PYTHON_VER = "3.12"
HOST = "localhost"

# ===============================================================================
#  Setting Up Development Envrionment
# ===============================================================================
[tasks."env:install-uv"]
description = "Install uv package manager"
run = "curl -LsSf https://astral.sh/uv/install.sh | sh"

[tasks."env:venv"]
description = "Set up Python virtual environment"
depends = ["env:install-uv"]
run = "uv venv ${VENV} --python ${PYTHON_VER} && . ${VENV}/bin/activate && uv sync"

[tasks."env:gen-env"]
description = "Generate .env file from example.env"
run = "cp ./example.env ./.env"

[tasks."docker:start"]
description = "Start required Docker containers"
run = "docker-compose -f docker-compose.yaml up -d"

[tasks."browser:open"]
description = "Open browser for Milvus dashboard"
run = "open http://${HOST}:9091/webui"

# ===============================================================================
#  Dataset
# ===============================================================================
[tasks."dataset:prepare.for.build.rag"]
description = "Prepare the data Build-RAG.ipynb for notebooks"
run = """
ollama pull mxbai-embed-large && \
ollama pull gemma3:latest && \
brew install wget && \
wget https://github.com/milvus-io/milvus-docs/releases/download/v2.4.6-preview/milvus_docs_2.4.x_en.zip && \
unzip -q milvus_docs_2.4.x_en.zip -d milvus_docs && \
. ${VENV}/bin/activate && \
uv sync --group tutorials
"""

[tasks."dataset:image.search.dataset"]
description = "Image search dataseet"
run = """
wget https://github.com/milvus-io/pymilvus-assets/releases/download/imagedata/reverse_image_search.zip && \
mkdir -p image-search-dataset && \
cp ./reverse_image_search.zip ./image-search-dataset/reverse_image_search.zip && \
cd image-search-dataset && \
unzip -q -o reverse_image_search.zip && \
rm -r reverse_image_search.zip && \
cd .. && \
rm -r reverse_image_search.zip
"""

# ===============================================================================
#  Running Examples
# ===============================================================================
[tasks."examples.py.01.build.rag"]
description = "Example 01 - Build RAG"
run = """
. ${VENV}/bin/activate && \
uv sync && \
cd ./demo/py/ && \
uv run 01-build-rag.py
"""

[tasks."examples.py.02.full.text.search"]
description = "Example 02 - Full Text Search"
run = """
. ${VENV}/bin/activate && \
uv sync && \
cd ./demo/py/ && \
uv run 02-full-text-search.py
"""

[tasks."examples.py.03.hybrid.search"]
description = "Example 03 - Hybrid Search"
run = """
. ${VENV}/bin/activate && \
uv sync && \
cd ./demo/py/ && \
uv run 03-hybrid-search.py
"""

[tasks."examples.py.04.image.search"]
description = "Example 04 - Image Search"
run = """
. ${VENV}/bin/activate && \
uv sync && \
cd ./demo/py/ && \
uv run 04-image-search.py
"""

[tasks."examples.py.05.multimodal.rag"]
description = "Example 05 - Multimodal RAG"
run = """
. ${VENV}/bin/activate && \
uv sync && \
cd ./demo/py/ && \
uv run 05-multimodal-rag.py
"""

[tasks."examples.py.06.graph.rag"]
description = "Example 05 - Graph RAG"
run = """
. ${VENV}/bin/activate && \
uv sync && \
cd ./demo/py/ && \
uv run 06-graph-rag.py
"""