from typing import List, Dict, Any
import json


def load_td(path: str)-> Dict[str, Any]:
    with open(path, "r") as f:
        data = json.load(f)
    return data


def fields2str(fields: List[Dict[str, Any]])-> str:
    """테이블 설명 정보를 string으로 변환
    db_desc_gen으로 생성한 일부 정보에 대해 string으로 변환

    Parameters
    ----------
        fields: List[Dict[str, Any]]
            db_desc_gen으로 생성한 table description 의 fields.

    Returns
    -------
        str: 테이블 설명 정보.
    """   
    lines = []
    for field in fields:
        lines.append(f"Column {field.get("field_name", None)}")
        lines.append(f"- Type: {field.get("field_type", None)}")
        lines.append(f"- Description: {field.get("field_comment", None)}")
        lines.append(f"- Category: {field.get("category", None)}")
        lines.append(f"- Dimension or Measures: {field.get("dim_or_meas", None)}")
        if len(field.get("field_examples", None)) != 0:
            lines.append(f"- Examples: {field.get("field_examples", None)}")
        lines.append(f"- Distinct Count: {field.get("distinct_count", None)}")
        lines.append(f"- English Name: {field.get("full_en_col_name", None)}")
        lines.append(f"- Korean Name: {field.get("ko_col_name", None)}")
        lines.append("") 

    return "\n".join(lines)


def preprocess_td(data: Dict[str, Any])-> Dict[str, str]:
    """Preprocess Table Descriptions(td)

    각 테이블마다 table comment, column descriptions 순서로 분리해서 저장합니다.

    Parameters
    ----------
        data: str
            Data from json file. It was generated by description_generator.
        table_name: str
            Table name.

    Returns
    -------
        Dict[str, Dict[str, Union[str, List[Dict[str, Any]]]]]:
            Table comments(str) and column descriptions(pd.Dataframe) for each tables.
    """

    tables = data.get("tables", [])

    td = {}
    for table in tables:
        table_name = table.get("table_name")
        td[table_name] = {}
        td[table_name]["table_comment"] = table.get('table_comment', None)
        td[table_name]["column_description"] = fields2str(table.get('fields', None))
    return td


if __name__=="__main__":
    json_path = "shilla/experiments/data/_generated_schemas_shilla_t2s_devloper_gemma3_12b_20250528_shilla_t2s_devloper_gemma3_12b_20250528.json"
    data = load_td(json_path)
    td = preprocess_td(data)
    print(td)
